//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema2WindowsFormsAppClient.MoviesServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        private int DurationField;
        
        private System.DateTime ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int RatingField;
        
        private bool WatchedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Watched {
            get {
                return this.WatchedField;
            }
            set {
                if ((this.WatchedField.Equals(value) != true)) {
                    this.WatchedField = value;
                    this.RaisePropertyChanged("Watched");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MoviesServiceReference.MoviesWebServiceSoap")]
    public interface MoviesWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetMoviesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovies", ReplyAction="*")]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesResponse GetMovies(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesResponse> GetMoviesAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequest request);
        
        // CODEGEN: Generating message contract since element name GetWatchedMoviesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWatchedMovies", ReplyAction="*")]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesResponse GetWatchedMovies(Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWatchedMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesResponse> GetWatchedMoviesAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequest request);
        
        // CODEGEN: Generating message contract since element name GetUnwatchedMoviesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnwatchedMovies", ReplyAction="*")]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesResponse GetUnwatchedMovies(Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnwatchedMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesResponse> GetUnwatchedMoviesAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequest request);
        
        // CODEGEN: Generating message contract since element name GetMovieByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovieById", ReplyAction="*")]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdResponse GetMovieById(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovieById", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdResponse> GetMovieByIdAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovieByTitle", ReplyAction="*")]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleResponse GetMovieByTitle(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovieByTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleResponse> GetMovieByTitleAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequest request);
        
        // CODEGEN: Generating message contract since element name movie from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMovie", ReplyAction="*")]
        Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieResponse AddMovie(Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieResponse> AddMovieAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequest request);
        
        // CODEGEN: Generating message contract since element name movie from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMovie", ReplyAction="*")]
        Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieResponse UpdateMovie(Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieResponse> UpdateMovieAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequest request);
        
        // CODEGEN: Generating message contract since element name movie from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMovie", ReplyAction="*")]
        Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieResponse DeleteMovie(Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieResponse> DeleteMovieAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovies", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequestBody Body;
        
        public GetMoviesRequest() {
        }
        
        public GetMoviesRequest(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMoviesRequestBody {
        
        public GetMoviesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesResponseBody Body;
        
        public GetMoviesResponse() {
        }
        
        public GetMoviesResponse(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie[] GetMoviesResult;
        
        public GetMoviesResponseBody() {
        }
        
        public GetMoviesResponseBody(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie[] GetMoviesResult) {
            this.GetMoviesResult = GetMoviesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWatchedMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWatchedMovies", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequestBody Body;
        
        public GetWatchedMoviesRequest() {
        }
        
        public GetWatchedMoviesRequest(Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWatchedMoviesRequestBody {
        
        public GetWatchedMoviesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWatchedMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWatchedMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesResponseBody Body;
        
        public GetWatchedMoviesResponse() {
        }
        
        public GetWatchedMoviesResponse(Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWatchedMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie[] GetWatchedMoviesResult;
        
        public GetWatchedMoviesResponseBody() {
        }
        
        public GetWatchedMoviesResponseBody(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie[] GetWatchedMoviesResult) {
            this.GetWatchedMoviesResult = GetWatchedMoviesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnwatchedMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnwatchedMovies", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequestBody Body;
        
        public GetUnwatchedMoviesRequest() {
        }
        
        public GetUnwatchedMoviesRequest(Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUnwatchedMoviesRequestBody {
        
        public GetUnwatchedMoviesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnwatchedMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnwatchedMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesResponseBody Body;
        
        public GetUnwatchedMoviesResponse() {
        }
        
        public GetUnwatchedMoviesResponse(Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUnwatchedMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie[] GetUnwatchedMoviesResult;
        
        public GetUnwatchedMoviesResponseBody() {
        }
        
        public GetUnwatchedMoviesResponseBody(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie[] GetUnwatchedMoviesResult) {
            this.GetUnwatchedMoviesResult = GetUnwatchedMoviesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovieById", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequestBody Body;
        
        public GetMovieByIdRequest() {
        }
        
        public GetMovieByIdRequest(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMovieByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetMovieByIdRequestBody() {
        }
        
        public GetMovieByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovieByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdResponseBody Body;
        
        public GetMovieByIdResponse() {
        }
        
        public GetMovieByIdResponse(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMovieByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie GetMovieByIdResult;
        
        public GetMovieByIdResponseBody() {
        }
        
        public GetMovieByIdResponseBody(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie GetMovieByIdResult) {
            this.GetMovieByIdResult = GetMovieByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieByTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovieByTitle", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequestBody Body;
        
        public GetMovieByTitleRequest() {
        }
        
        public GetMovieByTitleRequest(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMovieByTitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public GetMovieByTitleRequestBody() {
        }
        
        public GetMovieByTitleRequestBody(string title) {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieByTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovieByTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleResponseBody Body;
        
        public GetMovieByTitleResponse() {
        }
        
        public GetMovieByTitleResponse(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMovieByTitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie GetMovieByTitleResult;
        
        public GetMovieByTitleResponseBody() {
        }
        
        public GetMovieByTitleResponseBody(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie GetMovieByTitleResult) {
            this.GetMovieByTitleResult = GetMovieByTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMovie", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequestBody Body;
        
        public AddMovieRequest() {
        }
        
        public AddMovieRequest(Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie;
        
        public AddMovieRequestBody() {
        }
        
        public AddMovieRequestBody(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie) {
            this.movie = movie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieResponseBody Body;
        
        public AddMovieResponse() {
        }
        
        public AddMovieResponse(Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddMovieResponseBody {
        
        public AddMovieResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMovie", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequestBody Body;
        
        public UpdateMovieRequest() {
        }
        
        public UpdateMovieRequest(Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie;
        
        public UpdateMovieRequestBody() {
        }
        
        public UpdateMovieRequestBody(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie) {
            this.movie = movie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieResponseBody Body;
        
        public UpdateMovieResponse() {
        }
        
        public UpdateMovieResponse(Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateMovieResponseBody {
        
        public UpdateMovieResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMovie", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequestBody Body;
        
        public DeleteMovieRequest() {
        }
        
        public DeleteMovieRequest(Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie;
        
        public DeleteMovieRequestBody() {
        }
        
        public DeleteMovieRequestBody(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie) {
            this.movie = movie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieResponseBody Body;
        
        public DeleteMovieResponse() {
        }
        
        public DeleteMovieResponse(Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteMovieResponseBody {
        
        public DeleteMovieResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MoviesWebServiceSoapChannel : Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MoviesWebServiceSoapClient : System.ServiceModel.ClientBase<Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap>, Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap {
        
        public MoviesWebServiceSoapClient() {
        }
        
        public MoviesWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MoviesWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoviesWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoviesWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesResponse Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetMovies(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequest request) {
            return base.Channel.GetMovies(request);
        }
        
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie[] GetMovies() {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequestBody();
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesResponse retVal = ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetMovies(inValue);
            return retVal.Body.GetMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesResponse> Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetMoviesAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequest request) {
            return base.Channel.GetMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesResponse> GetMoviesAsync() {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMoviesRequestBody();
            return ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetMoviesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesResponse Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetWatchedMovies(Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequest request) {
            return base.Channel.GetWatchedMovies(request);
        }
        
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie[] GetWatchedMovies() {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequestBody();
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesResponse retVal = ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetWatchedMovies(inValue);
            return retVal.Body.GetWatchedMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesResponse> Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetWatchedMoviesAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequest request) {
            return base.Channel.GetWatchedMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesResponse> GetWatchedMoviesAsync() {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetWatchedMoviesRequestBody();
            return ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetWatchedMoviesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesResponse Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetUnwatchedMovies(Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequest request) {
            return base.Channel.GetUnwatchedMovies(request);
        }
        
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie[] GetUnwatchedMovies() {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequestBody();
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesResponse retVal = ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetUnwatchedMovies(inValue);
            return retVal.Body.GetUnwatchedMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesResponse> Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetUnwatchedMoviesAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequest request) {
            return base.Channel.GetUnwatchedMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesResponse> GetUnwatchedMoviesAsync() {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetUnwatchedMoviesRequestBody();
            return ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetUnwatchedMoviesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdResponse Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetMovieById(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequest request) {
            return base.Channel.GetMovieById(request);
        }
        
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie GetMovieById(int id) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequestBody();
            inValue.Body.id = id;
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdResponse retVal = ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetMovieById(inValue);
            return retVal.Body.GetMovieByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdResponse> Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetMovieByIdAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequest request) {
            return base.Channel.GetMovieByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdResponse> GetMovieByIdAsync(int id) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByIdRequestBody();
            inValue.Body.id = id;
            return ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetMovieByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleResponse Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetMovieByTitle(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequest request) {
            return base.Channel.GetMovieByTitle(request);
        }
        
        public Tema2WindowsFormsAppClient.MoviesServiceReference.Movie GetMovieByTitle(string title) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequestBody();
            inValue.Body.title = title;
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleResponse retVal = ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetMovieByTitle(inValue);
            return retVal.Body.GetMovieByTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleResponse> Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.GetMovieByTitleAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequest request) {
            return base.Channel.GetMovieByTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleResponse> GetMovieByTitleAsync(string title) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.GetMovieByTitleRequestBody();
            inValue.Body.title = title;
            return ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).GetMovieByTitleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieResponse Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.AddMovie(Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequest request) {
            return base.Channel.AddMovie(request);
        }
        
        public void AddMovie(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequestBody();
            inValue.Body.movie = movie;
            Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieResponse retVal = ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).AddMovie(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieResponse> Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.AddMovieAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequest request) {
            return base.Channel.AddMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieResponse> AddMovieAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.AddMovieRequestBody();
            inValue.Body.movie = movie;
            return ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).AddMovieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieResponse Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.UpdateMovie(Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequest request) {
            return base.Channel.UpdateMovie(request);
        }
        
        public void UpdateMovie(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequestBody();
            inValue.Body.movie = movie;
            Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieResponse retVal = ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).UpdateMovie(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieResponse> Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.UpdateMovieAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequest request) {
            return base.Channel.UpdateMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieResponse> UpdateMovieAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.UpdateMovieRequestBody();
            inValue.Body.movie = movie;
            return ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).UpdateMovieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieResponse Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.DeleteMovie(Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequest request) {
            return base.Channel.DeleteMovie(request);
        }
        
        public void DeleteMovie(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequestBody();
            inValue.Body.movie = movie;
            Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieResponse retVal = ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).DeleteMovie(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieResponse> Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap.DeleteMovieAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequest request) {
            return base.Channel.DeleteMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieResponse> DeleteMovieAsync(Tema2WindowsFormsAppClient.MoviesServiceReference.Movie movie) {
            Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequest inValue = new Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequest();
            inValue.Body = new Tema2WindowsFormsAppClient.MoviesServiceReference.DeleteMovieRequestBody();
            inValue.Body.movie = movie;
            return ((Tema2WindowsFormsAppClient.MoviesServiceReference.MoviesWebServiceSoap)(this)).DeleteMovieAsync(inValue);
        }
    }
}
